services:
  mongodb:
    image: mongo:latest
    container_name: mymongo
    ports:
      - "27017:27017"
    volumes:
      - /Users/brandonma/Documents/Vandy/Fall24/NoSQL/MiniProject/MiniProject2:/ds5760/mongo